
import java.awt.Robot;
import java.awt.event.InputEvent;
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.ServerSocket;
import java.net.Socket;
import javax.swing.JOptionPane;

public class server {

    server() {
        try {
            ServerSocket sersock = new ServerSocket(8005);
            new server2();
            while (true) {
                Socket sock = sersock.accept();
                new Thread(new clientHandler(sock)).start();
            }
        } catch (IOException e) {
        }
    }

    class clientHandler implements Runnable {

        DataInputStream dis;
        DataOutputStream dos;

        clientHandler(Socket sock)  {
            try{
            dis = new DataInputStream(sock.getInputStream());
            dos = new DataOutputStream(sock.getOutputStream());
        }catch(Exception e)
        {
        e.printStackTrace();
        }
            }

        @Override
        public void run() {
            try {
                String s = dis.readLine();
                System.out.println(s);
                if (s.equals("checking server")) {
                    dos.writeBytes("Hello\r\n");
                }
                else if(s.equals("Mouse Clicked"))
                {
                int x= Integer.parseInt(dis.readLine());
                int y= Integer.parseInt(dis.readLine());
                int bt= Integer.parseInt(dis.readLine());
                System.out.println("x="+x);
                 System.out.println("y="+y);
                 Robot rb= new Robot();
                 rb.mouseMove(x,y);
                 if(bt==1)
                 {
                 rb.mousePress(InputEvent.BUTTON1_DOWN_MASK);
                 rb.mouseRelease(InputEvent.BUTTON1_DOWN_MASK);
                 }
                 else if (bt==3)
                 {
                 rb.mousePress(InputEvent.BUTTON3_DOWN_MASK);
                 rb.mouseRelease(InputEvent.BUTTON3_DOWN_MASK);
                 }
                } else if(s.equals("Mouse Moved"))
                {
                int x= Integer.parseInt(dis.readLine());
                int y= Integer.parseInt(dis.readLine());
               System.out.println("x="+x);
                 System.out.println("y="+y);
                 Robot rb= new Robot();
                 rb.mouseMove(x,y);
                }
                else if(s.equals("Key Pressed"))
                {
                int code= Integer.parseInt(dis.readLine());
                System.out.println(code);
                Robot rb =new Robot();
                rb.keyPress(code);
                }
                 else if(s.equals("Key Released"))
                {
                int code= Integer.parseInt(dis.readLine());
                System.out.println(code);
                Robot rb =new Robot();
                rb.keyRelease(code);
                }
                 else if(s.equals("Shut Down"))
                {
                Runtime.getRuntime().exec("shutdown /s");
                }
                else if(s.equals("Send Message"))
                {
                    
                message msg = new message();
                msg.jTextArea1.setText(dis.readLine());
                System.out.println(dis.readLine());
                
                
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    

public class message extends javax.swing.JFrame {

    /**
     * Creates new form message
     */
    public message() {
        
        initComponents();
        setVisible(true);
        setSize(600,600);
        jTextArea1.setFocusable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        jLabel1.setText("YOU HAVE A MESSAGE");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       this.dispose();
    }                                        

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration                   
}


    
    
    public static void main(String args[]) {
        new server();
    }

}
